$ErrorActionPreference = "Stop"
$L = @()
$L += '$ErrorActionPreference = "Stop"'
$L += ''
$L += '$histDir = Join-Path $PSScriptRoot "data\history"'
$L += '$curFiles = Get-ChildItem (Join-Path $histDir "*_CURRENT.json") | Sort-Object Name'
$L += 'Write-Host ("Found {0} CURRENT files to fix" -f $curFiles.Count)'
$L += ''
$L += '$utf8NoBom = New-Object System.Text.UTF8Encoding $false'
$L += ''
$L += 'foreach ($f in $curFiles) {'
$L += '    $raw = [System.IO.File]::ReadAllText($f.FullName, [System.Text.Encoding]::UTF8)'
$L += '    $d = $raw | ConvertFrom-Json'
$L += '    $fixedCount = 0'
$L += '    foreach ($h in $d.horses) {'
$L += '        if (-not $h.last_3) { continue }'
$L += '        $newLast3 = @()'
$L += '        $changed = $false'
$L += '        foreach ($el in $h.last_3) {'
$L += '            if ($el -is [PSCustomObject]) {'
$L += '                $newLast3 += $el'
$L += '            } else {'
$L += '                try { $fn = [int]$el } catch { $fn = 0 }'
$L += '                $newLast3 += [PSCustomObject]@{ finish = $fn }'
$L += '                $changed = $true'
$L += '            }'
$L += '        }'
$L += '        if ($changed) {'
$L += '            $h.last_3 = $newLast3'
$L += '            $fixedCount++'
$L += '        }'
$L += '    }'
$L += '    if ($fixedCount -gt 0) {'
$L += '        $json = $d | ConvertTo-Json -Depth 10'
$L += '        [System.IO.File]::WriteAllText($f.FullName, $json, $utf8NoBom)'
$L += '        Write-Host ("  FIXED {0}: {1} horses" -f $f.Name, $fixedCount)'
$L += '    } else {'
$L += '        Write-Host ("  OK {0}: no changes" -f $f.Name)'
$L += '    }'
$L += '}'
$L += ''
$L += 'Write-Host "Done."'
$L += 'exit 0'

$encBom = New-Object System.Text.UTF8Encoding $true
$outPath = Join-Path $PSScriptRoot "fix_current_last3.ps1"
[System.IO.File]::WriteAllText($outPath, ($L -join "`r`n"), $encBom)
$joined = $L -join ""
Write-Host ("Built: {0} (lines={1}, chars={2})" -f $outPath, $L.Count, $joined.Length)
