$ErrorActionPreference = "Stop"
$port = 9000
$rootDir = $PSScriptRoot
$codeLines = @()
$codeLines += 'Add-Type -AssemblyName System.Web'
$codeLines += '$port = ' + $port
$codeLines += '$logFile = Join-Path $PSScriptRoot "server.log"'
$codeLines += '$utf8NoBom = New-Object System.Text.UTF8Encoding $false'
$codeLines += '$nl = [Environment]::NewLine'
$codeLines += '$banner = "[" + (Get-Date) + "] Starting server on port " + $port + " (NO AUTH)" + $nl'
$codeLines += '[IO.File]::WriteAllText($logFile, $banner, $utf8NoBom)'
$codeLines += '$publicDir = Join-Path $PSScriptRoot "public"'
$codeLines += '$dataDir = Join-Path $PSScriptRoot "data"'
$codeLines += '$wildcardOk = $false'
$codeLines += '$prefix1 = "http://localhost:" + $port + "/"'
$codeLines += '$prefix2 = "http://127.0.0.1:" + $port + "/"'
$codeLines += '$prefix3 = "http://+:" + $port + "/"'
$codeLines += '$listener = New-Object System.Net.HttpListener'
$codeLines += 'try {'
$codeLines += '    $listener.Prefixes.Add($prefix3)'
$codeLines += '    try {'
$codeLines += '        $listener.Start()'
$codeLines += '        $wildcardOk = $true'
$codeLines += '        [IO.File]::AppendAllText($logFile, ("Added prefix: " + $prefix3 + " (ALL INTERFACES / WILDCARD + LAN / WAN ACCESS - STARTED OK)" + $nl), $utf8NoBom)'
$codeLines += '        [IO.File]::AppendAllText($logFile, ("SERVER STARTED OK (NO AUTH, wildcard +)" + $nl), $utf8NoBom)'
$codeLines += '    } catch {'
$codeLines += '        $line = "FAIL START wildcard (need Admin URL ACL): " + $_.Exception.Message + " --> fallback localhost only" + $nl'
$codeLines += '        [IO.File]::AppendAllText($logFile, $line, $utf8NoBom)'
$codeLines += '        try { $listener.Stop() } catch {}'
$codeLines += '        try { $listener.Close() } catch {}'
$codeLines += '        $listener = New-Object System.Net.HttpListener'
$codeLines += '        try {'
$codeLines += '            $listener.Prefixes.Add($prefix1)'
$codeLines += '            [IO.File]::AppendAllText($logFile, ("Added prefix: " + $prefix1 + " (fallback localhost only)" + $nl), $utf8NoBom)'
$codeLines += '        } catch {'
$codeLines += '            $line = "FAIL prefix " + $prefix1 + " : " + $_.Exception.Message + $nl'
$codeLines += '            [IO.File]::AppendAllText($logFile, $line, $utf8NoBom)'
$codeLines += '        }'
$codeLines += '        try {'
$codeLines += '            $listener.Prefixes.Add($prefix2)'
$codeLines += '            [IO.File]::AppendAllText($logFile, ("Added prefix: " + $prefix2 + $nl), $utf8NoBom)'
$codeLines += '        } catch {'
$codeLines += '            $line = "FAIL prefix " + $prefix2 + " : " + $_.Exception.Message + $nl'
$codeLines += '            [IO.File]::AppendAllText($logFile, $line, $utf8NoBom)'
$codeLines += '        }'
$codeLines += '        try {'
$codeLines += '            $listener.Start()'
$codeLines += '            [IO.File]::AppendAllText($logFile, ("SERVER STARTED OK (NO AUTH, localhost only)" + $nl), $utf8NoBom)'
$codeLines += '        } catch {'
$codeLines += '            $line = "FATAL START FAIL: " + $_.Exception.Message + $nl'
$codeLines += '            [IO.File]::AppendAllText($logFile, $line, $utf8NoBom)'
$codeLines += '            exit 1'
$codeLines += '        }'
$codeLines += '    }'
$codeLines += '} catch {'
$codeLines += '    $line = "FAIL prefix + wildcard add (non-admin normal): " + $_.Exception.Message + " --> fallback localhost only" + $nl'
$codeLines += '    [IO.File]::AppendAllText($logFile, $line, $utf8NoBom)'
$codeLines += '    try { $listener.Stop() } catch {}'
$codeLines += '    try { $listener.Close() } catch {}'
$codeLines += '    $listener = New-Object System.Net.HttpListener'
$codeLines += '    try {'
$codeLines += '        $listener.Prefixes.Add($prefix1)'
$codeLines += '        [IO.File]::AppendAllText($logFile, ("Added prefix: " + $prefix1 + " (fallback localhost only)" + $nl), $utf8NoBom)'
$codeLines += '    } catch {'
$codeLines += '        $line = "FAIL prefix " + $prefix1 + " : " + $_.Exception.Message + $nl'
$codeLines += '        [IO.File]::AppendAllText($logFile, $line, $utf8NoBom)'
$codeLines += '    }'
$codeLines += '    try {'
$codeLines += '        $listener.Prefixes.Add($prefix2)'
$codeLines += '        [IO.File]::AppendAllText($logFile, ("Added prefix: " + $prefix2 + $nl), $utf8NoBom)'
$codeLines += '    } catch {'
$codeLines += '        $line = "FAIL prefix " + $prefix2 + " : " + $_.Exception.Message + $nl'
$codeLines += '        [IO.File]::AppendAllText($logFile, $line, $utf8NoBom)'
$codeLines += '    }'
$codeLines += '    try {'
$codeLines += '        $listener.Start()'
$codeLines += '        [IO.File]::AppendAllText($logFile, ("SERVER STARTED OK (NO AUTH, localhost only)" + $nl), $utf8NoBom)'
$codeLines += '    } catch {'
$codeLines += '        $line = "FATAL START FAIL: " + $_.Exception.Message + $nl'
$codeLines += '        [IO.File]::AppendAllText($logFile, $line, $utf8NoBom)'
$codeLines += '        exit 1'
$codeLines += '    }'
$codeLines += '}'
$codeLines += 'function WriteBanner() {'
$codeLines += '    Write-Host "=============================================================" -ForegroundColor Cyan'
$codeLines += '    $baLine = "= SERVER RUNNING http://localhost:" + $port + " (NO AUTH REQUIRED) ="'
$codeLines += '    Write-Host $baLine -ForegroundColor Cyan'
$codeLines += '    Write-Host ("  Local:    http://localhost:" + $port)'
$codeLines += '    $myIPs = @(Get-NetIPAddress -AddressFamily IPv4 -ErrorAction SilentlyContinue | Where-Object { $_.IPAddress -notlike "127.*" -and $_.IPAddress -notlike "169.254.*" } | Select-Object -ExpandProperty IPAddress)'
$codeLines += '    if (-not $myIPs) { $myIPs = @() }'
$codeLines += '    if ($wildcardOk -and $myIPs.Count -gt 0) {'
$codeLines += '        foreach ($ip in $myIPs) { Write-Host ("  LAN:      http://" + $ip + ":" + $port) -ForegroundColor Yellow }'
$codeLines += '        Write-Host "  PWA LAN:  Open the above LAN URL on mobile WiFi -> Share -> Add to Home Screen" -ForegroundColor Yellow'
$codeLines += '    } else {'
$codeLines += '        Write-Host ("  LAN/WAN:  Disabled (run PowerShell as ADMIN once, then execute:")'
$codeLines += '        Write-Host ("             netsh http add urlacl url=http://+:" + $port + "/ user=Everyone")'
$codeLines += '        Write-Host "             After restarting server, LAN access becomes available" -ForegroundColor DarkYellow'
$codeLines += '        Write-Host "  Ngrok:    ngrok http 9000 --basic-auth=`"user:pass`"   (WAN PWA access for mobile)"'
$codeLines += '        Write-Host "  PWA WAN:  Use Ngrok HTTPS URL on mobile to Install App"'
$codeLines += '    }'
$codeLines += '    Write-Host "  Endpoint: GET /api/refresh to trigger data sync"'
$codeLines += '    Write-Host "============================================================="'
$codeLines += '}'
$codeLines += 'WriteBanner'
$codeLines += '$script:refreshRunning = $false'
$codeLines += '$script:lastRefreshResult = $null'
$codeLines += '$handlerPath = Join-Path $PSScriptRoot "api_refresh_handler.ps1"'
$codeLines += '$mimeHtml = "text/html; charset=utf-8"'
$codeLines += '$mimeJs = "application/javascript; charset=utf-8"'
$codeLines += '$mimeCss = "text/css; charset=utf-8"'
$codeLines += '$mimeJson = "application/json; charset=utf-8"'
$codeLines += '$mimePng = "image/png"'
$codeLines += '$mimeJpg = "image/jpeg"'
$codeLines += '$mimeSvg = "image/svg+xml"'
$codeLines += '$mimeCsv = "text/csv; charset=utf-8"'
$codeLines += '$mimeIco = "image/x-icon"'
$codeLines += '$mimeOct = "application/octet-stream"'
$codeLines += 'function GetCType([string]$ext) {'
$codeLines += '    if ($ext -eq ".html") { return $mimeHtml }'
$codeLines += '    if ($ext -eq ".js") { return $mimeJs }'
$codeLines += '    if ($ext -eq ".css") { return $mimeCss }'
$codeLines += '    if ($ext -eq ".json") { return $mimeJson }'
$codeLines += '    if ($ext -eq ".png") { return $mimePng }'
$codeLines += '    if ($ext -eq ".jpg") { return $mimeJpg }'
$codeLines += '    if ($ext -eq ".svg") { return $mimeSvg }'
$codeLines += '    if ($ext -eq ".csv") { return $mimeCsv }'
$codeLines += '    if ($ext -eq ".ico") { return $mimeIco }'
$codeLines += '    return $mimeOct'
$codeLines += '}'
$codeLines += 'function ResolveApiPath([string]$path) {'
$codeLines += '    $hp = "/api/history/"'
$codeLines += '    $pp = "/api/profiles/"'
$codeLines += '    $sp = "/api/stats/"'
$codeLines += '    $rp = "/api/references/"'
$codeLines += '    $tp = "/api/trackwork/"'
$codeLines += '    if ($path.StartsWith($hp)) {'
$codeLines += '        $fn = $path.Substring($hp.Length)'
$codeLines += '        $p1 = Join-Path $dataDir ("history\" + $fn)'
$codeLines += '        if (Test-Path $p1 -PathType Leaf) { return $p1 }'
$codeLines += '        $p2 = Join-Path $publicDir ("data\history\" + $fn)'
$codeLines += '        if (Test-Path $p2 -PathType Leaf) { return $p2 }'
$codeLines += '        return $null'
$codeLines += '    }'
$codeLines += '    if ($path -eq "/api/profiles/horses" -or $path -eq "/api/profiles/horses/") {'
$codeLines += '        $p1 = Join-Path $dataDir "profiles\horses_db.json"'
$codeLines += '        if (Test-Path $p1 -PathType Leaf) { return $p1 }'
$codeLines += '        $p2 = Join-Path $publicDir "data\profiles\horses_db.json"'
$codeLines += '        if (Test-Path $p2 -PathType Leaf) { return $p2 }'
$codeLines += '        return $null'
$codeLines += '    }'
$codeLines += '    if ($path.StartsWith($pp)) {'
$codeLines += '        $fn = $path.Substring($pp.Length)'
$codeLines += '        if ([string]::IsNullOrWhiteSpace($fn)) { $fn = "horses_db.json" }'
$codeLines += '        $p1 = Join-Path $dataDir ("profiles\" + $fn)'
$codeLines += '        if (Test-Path $p1 -PathType Leaf) { return $p1 }'
$codeLines += '        $p2 = Join-Path $publicDir ("data\profiles\" + $fn)'
$codeLines += '        if (Test-Path $p2 -PathType Leaf) { return $p2 }'
$codeLines += '        return $null'
$codeLines += '    }'
$codeLines += '    if ($path.StartsWith($sp)) {'
$codeLines += '        $fn = $path.Substring($sp.Length)'
$codeLines += '        $p1 = Join-Path $dataDir ("stats\" + $fn)'
$codeLines += '        if (Test-Path $p1 -PathType Leaf) { return $p1 }'
$codeLines += '        $p2 = Join-Path $publicDir ("data\stats\" + $fn)'
$codeLines += '        if (Test-Path $p2 -PathType Leaf) { return $p2 }'
$codeLines += '        return $null'
$codeLines += '    }'
$codeLines += '    if ($path.StartsWith($rp)) {'
$codeLines += '        $fn = $path.Substring($rp.Length)'
$codeLines += '        $p1 = Join-Path $dataDir ("references\" + $fn)'
$codeLines += '        if (Test-Path $p1 -PathType Leaf) { return $p1 }'
$codeLines += '        $p2 = Join-Path $publicDir ("data\references\" + $fn)'
$codeLines += '        if (Test-Path $p2 -PathType Leaf) { return $p2 }'
$codeLines += '        return $null'
$codeLines += '    }'
$codeLines += '    if ($path.StartsWith($tp)) {'
$codeLines += '        $fn = $path.Substring($tp.Length)'
$codeLines += '        $p1 = Join-Path $dataDir ("trackwork\" + $fn)'
$codeLines += '        if (Test-Path $p1 -PathType Leaf) { return $p1 }'
$codeLines += '        $p2 = Join-Path $publicDir ("data\trackwork\" + $fn)'
$codeLines += '        if (Test-Path $p2 -PathType Leaf) { return $p2 }'
$codeLines += '        return $null'
$codeLines += '    }'
$codeLines += '    if ($path -eq "/api/races" -or $path -eq "/api/races/" -or $path -eq "/api/list") {'
$codeLines += '        $hist = Join-Path $publicDir "data\history"'
$codeLines += '        if (Test-Path $hist) {'
$codeLines += '            $files = Get-ChildItem $hist -Filter "*.json" | Sort-Object Name'
$codeLines += '            $list = @()'
$codeLines += '            foreach ($f in $files) { $list += $f.Name }'
$codeLines += '            return ,@($list,$true)'
$codeLines += '        }'
$codeLines += '        return $null'
$codeLines += '    }'
$codeLines += '    return $null'
$codeLines += '}'
$codeLines += 'function SendJson($Response, $Object, [int]$Depth) {'
$codeLines += '    $jsonBody = ConvertTo-Json $Object -Depth $Depth -Compress'
$codeLines += '    $bytes = $utf8NoBom.GetBytes($jsonBody)'
$codeLines += '    $Response.ContentType = $mimeJson'
$codeLines += '    $Response.ContentLength64 = $bytes.Length'
$codeLines += '    $Response.AddHeader("Cache-Control", "no-cache")'
$codeLines += '    $Response.AddHeader("Access-Control-Allow-Origin", "*")'
$codeLines += '    $Response.OutputStream.Write($bytes, 0, $bytes.Length)'
$codeLines += '    return $bytes.Length'
$codeLines += '}'
$codeLines += 'while ($listener.IsListening) {'
$codeLines += '    try {'
$codeLines += '        $ctx = $listener.GetContext()'
$codeLines += '        $req = $ctx.Request'
$codeLines += '        $res = $ctx.Response'
$codeLines += '        $path = [System.Web.HttpUtility]::UrlDecode($req.Url.AbsolutePath)'
$codeLines += '        if ($path -eq "/") { $path = "/index.html" }'
$codeLines += '        $clientIP = $req.RemoteEndPoint.Address.ToString()'
$codeLines += '        $stamp = Get-Date -Format HH:mm:ss'
$codeLines += '        if ($path -eq "/api/refresh" -or $path -eq "/api/refresh/") {'
$codeLines += '            try {'
$codeLines += '                if ($script:refreshRunning) {'
$codeLines += '                    $busyObj = New-Object PSObject'
$codeLines += '                    $busyObj | Add-Member NoteProperty ok $false'
$codeLines += '                    $busyObj | Add-Member NoteProperty status "running"'
$codeLines += '                    $busyObj | Add-Member NoteProperty message "Data sync in progress"'
$codeLines += '                    $busyObj | Add-Member NoteProperty last_result $script:lastRefreshResult'
$codeLines += '                    [void](SendJson -Response $res -Object $busyObj -Depth 6)'
$codeLines += '                    $busyLine = "[" + $stamp + "] " + $clientIP + "  202 BUSY   /api/refresh"'
$codeLines += '                    Write-Host $busyLine -ForegroundColor Yellow'
$codeLines += '                    $res.OutputStream.Close()'
$codeLines += '                    continue'
$codeLines += '                }'
$codeLines += '                $script:refreshRunning = $true'
$codeLines += '                $startLine = "[" + $stamp + "] " + $clientIP + "  START   /api/refresh"'
$codeLines += '                Write-Host $startLine -ForegroundColor Cyan'
$codeLines += '                $handlerOut = & powershell.exe -NoProfile -NonInteractive -ExecutionPolicy Bypass -File $handlerPath'
$codeLines += '                $handlerJson = ($handlerOut | Out-String).Trim()'
$codeLines += '                $parseOk = $false'
$codeLines += '                $outObj = $null'
$codeLines += '                try {'
$codeLines += '                    $outObj = $handlerJson | ConvertFrom-Json -ErrorAction Stop'
$codeLines += '                    if ($outObj) { $parseOk = $true }'
$codeLines += '                } catch { $parseOk = $false }'
$codeLines += '                if (-not $parseOk) {'
$codeLines += '                    $outObj = New-Object PSObject'
$codeLines += '                    $outObj | Add-Member NoteProperty ok $false'
$codeLines += '                    $outObj | Add-Member NoteProperty message "handler parse failed"'
$codeLines += '                    if ($handlerJson) {'
$codeLines += '                        $mx = [Math]::Min(400, $handlerJson.Length)'
$codeLines += '                        $snippet = $handlerJson.Substring(0, $mx)'
$codeLines += '                        $outObj | Add-Member NoteProperty raw $snippet'
$codeLines += '                    }'
$codeLines += '                }'
$codeLines += '                $script:lastRefreshResult = $outObj'
$codeLines += '                $script:refreshRunning = $false'
$codeLines += '                [void](SendJson -Response $res -Object $outObj -Depth 10)'
$codeLines += '                $isOk = $false'
$codeLines += '                try {'
$codeLines += '                    $okProp = $outObj | Select-Object -ExpandProperty ok -ErrorAction Stop'
$codeLines += '                    if ($okProp -eq $true) { $isOk = $true }'
$codeLines += '                } catch { $isOk = $false }'
$codeLines += '                if ($isOk) { $logColor = [ConsoleColor]::Green } else { $logColor = [ConsoleColor]::Red }'
$codeLines += '                $durDisp = "n/a"'
$codeLines += '                try {'
$codeLines += '                    $durProp = $outObj | Select-Object -ExpandProperty duration_sec -ErrorAction Stop'
$codeLines += '                    $durDisp = $durProp.ToString() + " sec"'
$codeLines += '                } catch {}'
$codeLines += '                $st2 = Get-Date -Format HH:mm:ss'
$codeLines += '                $doneLine = "[" + $st2 + "] " + $clientIP + "  DONE    /api/refresh [" + $durDisp + "]"'
$codeLines += '                Write-Host $doneLine -ForegroundColor $logColor'
$codeLines += '                $res.OutputStream.Close()'
$codeLines += '                continue'
$codeLines += '            } catch {'
$codeLines += '                $script:refreshRunning = $false'
$codeLines += '                $errTxt = $_.Exception.Message'
$codeLines += '                $errObj = New-Object PSObject'
$codeLines += '                $errObj | Add-Member NoteProperty ok $false'
$codeLines += '                $errObj | Add-Member NoteProperty error $errTxt'
$codeLines += '                [void](SendJson -Response $res -Object $errObj -Depth 5)'
$codeLines += '                $st3 = Get-Date -Format HH:mm:ss'
$codeLines += '                $failLine = "[" + $st3 + "] " + $clientIP + "  500 FAIL  /api/refresh : " + $errTxt'
$codeLines += '                Write-Host $failLine -ForegroundColor Red'
$codeLines += '                $res.OutputStream.Close()'
$codeLines += '                continue'
$codeLines += '            }'
$codeLines += '        }'
$codeLines += '        $resolved = ResolveApiPath $path'
$codeLines += '        $file = $null'
$codeLines += '        $isApiList = $false'
$codeLines += '        if ($resolved -is [array] -and $resolved.Count -ge 2 -and $resolved[1] -eq $true) {'
$codeLines += '            $isApiList = $true'
$codeLines += '            $blen = SendJson -Response $res -Object $resolved[0] -Depth 3'
$codeLines += '            $szStr = $blen.ToString() + " bytes"'
$codeLines += '            $apiLine = "[" + $stamp + "] " + $clientIP + "  200 API  " + $path + " [" + $szStr + "]"'
$codeLines += '            Write-Host $apiLine -ForegroundColor Green'
$codeLines += '            $res.OutputStream.Close()'
$codeLines += '            continue'
$codeLines += '        } elseif ($resolved) {'
$codeLines += '            $file = $resolved'
$codeLines += '        } else {'
$codeLines += '            $file = Join-Path $publicDir $path.TrimStart("/")'
$codeLines += '        }'
$codeLines += '        if ($file -and (Test-Path $file -PathType Leaf)) {'
$codeLines += '            $ext = [System.IO.Path]::GetExtension($file).ToLower()'
$codeLines += '            $ctype = GetCType $ext'
$codeLines += '            $bytes = [System.IO.File]::ReadAllBytes($file)'
$codeLines += '            $res.ContentType = $ctype'
$codeLines += '            $res.ContentLength64 = $bytes.Length'
$codeLines += '            $res.AddHeader("Cache-Control", "no-cache")'
$codeLines += '            $res.AddHeader("Access-Control-Allow-Origin", "*")'
$codeLines += '            $res.OutputStream.Write($bytes, 0, $bytes.Length)'
$codeLines += '            $isJson = $false'
$codeLines += '            if ($ext -eq ".json") { $isJson = $true }'
$codeLines += '            if ($resolved) { $isJson = $true }'
$codeLines += '            $okLine = "[" + $stamp + "] " + $clientIP + "  200 OK   " + $path'
$codeLines += '            if ($isJson) { Write-Host $okLine -ForegroundColor Green } else { Write-Host $okLine }'
$codeLines += '        } else {'
$codeLines += '            $msgText = "404 Not Found: " + $path'
$codeLines += '            $msgBytes = $utf8NoBom.GetBytes($msgText)'
$codeLines += '            $res.StatusCode = 404'
$codeLines += '            $res.ContentType = "text/plain; charset=utf-8"'
$codeLines += '            $res.ContentLength64 = $msgBytes.Length'
$codeLines += '            $res.OutputStream.Write($msgBytes, 0, $msgBytes.Length)'
$codeLines += '            $nfLine = "[" + $stamp + "] " + $clientIP + "  404      " + $path'
$codeLines += '            Write-Host $nfLine -ForegroundColor Red'
$codeLines += '        }'
$codeLines += '        $res.OutputStream.Close()'
$codeLines += '    } catch {'
$codeLines += '        $errTxt = $_.Exception.Message'
$codeLines += '        $errMsg = "ERROR: " + $errTxt'
$codeLines += '        Write-Host $errMsg -ForegroundColor Red'
$codeLines += '        try {'
$codeLines += '            $dtm = Get-Date'
$codeLines += '            $sb = New-Object System.Text.StringBuilder'
$codeLines += '            [void]$sb.Append("LOG [")'
$codeLines += '            [void]$sb.Append($dtm)'
$codeLines += '            [void]$sb.Append("] EXCEPTION: ")'
$codeLines += '            [void]$sb.Append($errTxt)'
$codeLines += '            [void]$sb.Append($nl)'
$codeLines += '            $logLine = $sb.ToString()'
$codeLines += '            [IO.File]::AppendAllText($logFile, $logLine, $utf8NoBom)'
$codeLines += '        } catch {}'
$codeLines += '    }'
$codeLines += '}'
$serverCode = $codeLines -join [Environment]::NewLine
$outPath = Join-Path $rootDir "server_plain.ps1"
[IO.File]::WriteAllText($outPath, $serverCode, (New-Object System.Text.UTF8Encoding $false))
Write-Host ("BUILD OK: wrote " + $outPath + " (" + $serverCode.Length + " chars)")
Get-NetTCPConnection -LocalPort $port -ErrorAction SilentlyContinue | Select-Object OwningProcess | ForEach-Object { Stop-Process -Id $_.OwningProcess -Force -ErrorAction SilentlyContinue }
Start-Sleep -Seconds 2
Write-Host "Starting server..."
& powershell.exe -NoProfile -NonInteractive -ExecutionPolicy Bypass -File $outPath
