$ErrorActionPreference = "Stop"

$C_RN = "`r`n"
$L = @()

$L += '$ErrorActionPreference = "Stop"'
$L += ''
$L += '$histDir = Join-Path $PSScriptRoot "data\history"'
$L += '$profilesDir = Join-Path $PSScriptRoot "data\profiles"'
$L += '$statsDir = Join-Path $PSScriptRoot "data\stats"'
$L += ''
$L += 'if (-not (Test-Path $profilesDir)) { New-Item -ItemType Directory -Path $profilesDir -Force | Out-Null }'
$L += 'if (-not (Test-Path $statsDir)) { New-Item -ItemType Directory -Path $statsDir -Force | Out-Null }'
$L += ''
$L += '$utf8NoBom = New-Object System.Text.UTF8Encoding $false'
$L += ''
$L += '# Load all finished races (exclude CURRENT and summary)'
$L += '$allFiles = Get-ChildItem (Join-Path $histDir "*.json") | Where-Object { $_.Name -notmatch "_CURRENT\.json$" -and $_.Name -notmatch "_scrape_summary\.json$" } | Sort-Object Name'
$L += 'Write-Host ("Total JSON files found: {0}" -f $allFiles.Count)'
$L += ''
$L += '$finished = @()'
$L += 'foreach ($f in $allFiles) {'
$L += '    try {'
$L += '        $raw = [System.IO.File]::ReadAllText($f.FullName, [System.Text.Encoding]::UTF8)'
$L += '        $d = $raw | ConvertFrom-Json'
$L += '        if ($d.race_info -and $d.race_info.result_available -eq $true -and $d.race_info.official_result.Count -gt 0) {'
$L += '            $finished += $d'
$L += '        }'
$L += '    } catch {'
$L += '        Write-Host ("  SKIP bad JSON: {0}" -f $f.Name)'
$L += '    }'
$L += '}'
$L += ''
$L += '# Sort chronologically by date asc, race_number asc'
$L += '$finished = $finished | Sort-Object { $_.race_info.race_date }, { [int]$_.race_info.race_number }'
$L += 'Write-Host ("Valid finished races with results: {0}" -f $finished.Count)'
$L += ''
$L += '# Aggregate dictionaries'
$L += '$jockeys = @{}'
$L += '$trainers = @{}'
$L += '$horses = @{}'
$L += '$horseDist = @{}'  # horse_code -> { distance_m -> {starts, sum_finish, wins} }
$L += '$jockeyHorse = @{}' # "jockey|horse" -> {starts, wins}
$L += ''
$L += 'function GetOrAdd($dict, $key, $default) {'
$L += '    if (-not $dict.ContainsKey($key)) { $dict[$key] = & $default }'
$L += '    return $dict[$key]'
$L += '}'
$L += ''
$L += 'foreach ($race in $finished) {'
$L += '    $ri = $race.race_info'
$L += '    $dist = [int]$ri.distance_m'
$L += '    $date = $ri.race_date'
$L += '    $rn = [int]$ri.race_number'
$L += '    # Build lookup from official_result: code -> finish'
$L += '    $resLookup = @{}'
$L += '    foreach ($r in $ri.official_result) {'
$L += '        try { $fc = [int]$r.finish } catch { $fc = 99 }'
$L += '        $key = [string]$r.code'
$L += '        if ($key -and $key -ne "") { $resLookup[$key] = [PSCustomObject]@{ finish = $fc } }'
$L += '    }'
$L += '    # Iterate horses array (has jockey/trainer/best_time/finish)'
$L += '    foreach ($h in $race.horses) {'
$L += '        $hc = [string]$h.code'
$L += '        $hname = [string]$h.name'
$L += '        $jok = [string]$h.jockey'
$L += '        $trn = [string]$h.trainer'
$L += '        if (-not $hc -or $hc -eq "") { continue }'
$L += '        $finish = 99'
$L += '        # Priority 1: horses.finish (direct field from scraper)'
$L += '        if ($h.PSObject.Properties["finish"] -and $h.finish) {'
$L += '            try { $finish = [int]$h.finish } catch {}'
$L += '        }'
$L += '        # Priority 2: official_result lookup (fallback)'
$L += '        if ($finish -ge 99 -and $resLookup.ContainsKey($hc)) {'
$L += '            $finish = $resLookup[$hc].finish'
$L += '        }'
$L += '        $won = ($finish -eq 1)'
$L += '        $inq = ($finish -ge 1 -and $finish -le 4)'
$L += ''
$L += '        # Jockey'
$L += '        if ($jok -and $jok -ne "") {'
$L += '            $j = GetOrAdd $jockeys $jok { [PSCustomObject]@{ starts=0; wins=0; q_count=0 } }'
$L += '            $j.starts++'
$L += '            if ($won) { $j.wins++ }'
$L += '            if ($inq) { $j.q_count++ }'
$L += '        }'
$L += ''
$L += '        # Trainer'
$L += '        if ($trn -and $trn -ne "") {'
$L += '            $t = GetOrAdd $trainers $trn { [PSCustomObject]@{ starts=0; wins=0; q_count=0 } }'
$L += '            $t.starts++'
$L += '            if ($won) { $t.wins++ }'
$L += '            if ($inq) { $t.q_count++ }'
$L += '        }'
$L += ''
$L += '        # Horse'
$L += '        $hs = GetOrAdd $horses $hc { [PSCustomObject]@{ name=$hname; starts=0; wins=0; q_count=0; sum_finish=0; best_time=[double]::MaxValue; ratings=@(); last_run=""; last_place=0 } }'
$L += '        if (-not $hs.name -or $hs.name -eq "") { $hs.name = $hname }'
$L += '        $hs.starts++'
$L += '        if ($won) { $hs.wins++ }'
$L += '        if ($inq) { $hs.q_count++ }'
$L += '        if ($finish -lt 99) { $hs.sum_finish += $finish }'
$L += '        if ($h.best_time_sec -and [double]$h.best_time_sec -gt 0 -and [double]$h.best_time_sec -lt $hs.best_time) { $hs.best_time = [double]$h.best_time_sec }'
$L += '        if ($h.rating) { $hs.ratings += [int]$h.rating }'
$L += '        $hs.last_run = $date'
$L += '        if ($finish -lt 99) { $hs.last_place = $finish }'
$L += ''
$L += '        # Horse x Distance'
$L += '        $hd = GetOrAdd $horseDist $hc { @{} }'
$L += '        $dk = [string]$dist'
$L += '        $dobj = GetOrAdd $hd $dk { [PSCustomObject]@{ starts=0; sum_finish=0; wins=0 } }'
$L += '        $dobj.starts++'
$L += '        if ($finish -lt 99) { $dobj.sum_finish += $finish }'
$L += '        if ($won) { $dobj.wins++ }'
$L += ''
$L += '        # Jockey x Horse'
$L += '        if ($jok -and $jok -ne "") {'
$L += '            $jk = "{0}|{1}" -f $jok, $hc'
$L += '            $jh = GetOrAdd $jockeyHorse $jk { [PSCustomObject]@{ starts=0; wins=0 } }'
$L += '            $jh.starts++'
$L += '            if ($won) { $jh.wins++ }'
$L += '        }'
$L += '    }'
$L += '}'
$L += ''
$L += '# Post-process: compute rates (copy keys to array first - avoid Collection modified error)'
$L += '$jkeys = @($jockeys.Keys)'
$L += 'foreach ($k in $jkeys) {'
$L += '    $j = $jockeys[$k]'
$L += '    $wr = if ($j.starts -gt 0) { [double]$j.wins / $j.starts } else { 0.0 }'
$L += '    $qr = if ($j.starts -gt 0) { [double]$j.q_count / $j.starts } else { 0.0 }'
$L += '    $jockeys[$k] = [PSCustomObject]@{ starts=$j.starts; wins=$j.wins; q_count=$j.q_count; win_rate=[math]::Round($wr,6); q_rate=[math]::Round($qr,6) }'
$L += '}'
$L += ''
$L += '$tkeys = @($trainers.Keys)'
$L += 'foreach ($k in $tkeys) {'
$L += '    $t = $trainers[$k]'
$L += '    $wr = if ($t.starts -gt 0) { [double]$t.wins / $t.starts } else { 0.0 }'
$L += '    $qr = if ($t.starts -gt 0) { [double]$t.q_count / $t.starts } else { 0.0 }'
$L += '    $trainers[$k] = [PSCustomObject]@{ starts=$t.starts; wins=$t.wins; q_count=$t.q_count; win_rate=[math]::Round($wr,6); q_rate=[math]::Round($qr,6) }'
$L += '}'
$L += ''
$L += '$hkeys = @($horses.Keys)'
$L += 'foreach ($k in $hkeys) {'
$L += '    $h = $horses[$k]'
$L += '    $avgF = if ($h.starts -gt 0 -and $h.sum_finish -gt 0) { [math]::Round([double]$h.sum_finish / $h.starts, 3) } else { 0.0 }'
$L += '    $bt = if ($h.best_time -lt [double]::MaxValue) { [math]::Round($h.best_time, 3) } else { 0.0 }'
$L += '    $rAvg = 0.0; if ($h.ratings.Count -gt 0) { $sumR = 0; foreach ($r in $h.ratings) { $sumR += $r }; $rAvg = [math]::Round([double]$sumR / $h.ratings.Count, 1) }'
$L += '    $horses[$k] = [PSCustomObject]@{ name=$h.name; starts=$h.starts; wins=$h.wins; q_count=$h.q_count; avg_finish=$avgF; best_time=$bt; rating_avg=$rAvg; last_run=$h.last_run; last_place=$h.last_place }'
$L += '}'
$L += ''
$L += '$hdkeys = @($horseDist.Keys)'
$L += 'foreach ($hc in $hdkeys) {'
$L += '    $dk = $horseDist[$hc]'
$L += '    $outObj = @{}'
$L += '    $dkeys = @($dk.Keys)'
$L += '    foreach ($d in $dkeys) {'
$L += '        $o = $dk[$d]'
$L += '        $af = if ($o.starts -gt 0 -and $o.sum_finish -gt 0) { [math]::Round([double]$o.sum_finish / $o.starts, 3) } else { 0.0 }'
$L += '        $outObj[$d] = [PSCustomObject]@{ starts=$o.starts; avg_finish=$af; wins=$o.wins }'
$L += '    }'
$L += '    $horseDist[$hc] = [PSCustomObject]$outObj'
$L += '}'
$L += ''
$L += '$jhkeys = @($jockeyHorse.Keys)'
$L += 'foreach ($k in $jhkeys) {'
$L += '    $o = $jockeyHorse[$k]'
$L += '    $wr = if ($o.starts -gt 0) { [math]::Round([double]$o.wins / $o.starts, 6) } else { 0.0 }'
$L += '    $jockeyHorse[$k] = [PSCustomObject]@{ starts=$o.starts; wins=$o.wins; win_rate=$wr }'
$L += '}'
$L += ''
$L += '# Wrap in structure matching app.js expectations: {jockeys:...} / {trainers:...} / {horses:...}'
$L += '$ts = Get-Date -Format "yyyy-MM-dd HH:mm:ss"'
$L += '$jockeysFinal = [PSCustomObject]@{ meta=[PSCustomObject]@{ generated_at=$ts; source_races=$finished.Count }; jockeys=[PSCustomObject]$jockeys }'
$L += '$trainersFinal = [PSCustomObject]@{ meta=[PSCustomObject]@{ generated_at=$ts; source_races=$finished.Count }; trainers=[PSCustomObject]$trainers }'
$L += '$horsesFinal = [PSCustomObject]@{ meta=[PSCustomObject]@{ generated_at=$ts; source_races=$finished.Count }; horses=[PSCustomObject]$horses }'
$L += '$hdFinal = [PSCustomObject]@{ meta=[PSCustomObject]@{ generated_at=$ts; source_races=$finished.Count }; horseDistance=[PSCustomObject]$horseDist }'
$L += '$jhFinal = [PSCustomObject]@{ meta=[PSCustomObject]@{ generated_at=$ts; source_races=$finished.Count }; jockeyHorse=[PSCustomObject]$jockeyHorse }'
$L += ''
$L += 'function Write-JsonSafe($path, $obj) {'
$L += '    $json = $obj | ConvertTo-Json -Depth 10'
$L += '    [System.IO.File]::WriteAllText($path, $json, $utf8NoBom)'
$L += '    $sz = (Get-Item $path).Length'
$L += '    Write-Host ("  WROTE {0} ({1} bytes)" -f [System.IO.Path]::GetFileName($path), $sz)'
$L += '}'
$L += ''
$L += 'Write-Host "Writing aggregate DBs..."'
$L += 'Write-JsonSafe (Join-Path $statsDir "jockeys_db.json") $jockeysFinal'
$L += 'Write-JsonSafe (Join-Path $statsDir "trainers_db.json") $trainersFinal'
$L += 'Write-JsonSafe (Join-Path $profilesDir "horses_db.json") $horsesFinal'
$L += 'Write-JsonSafe (Join-Path $statsDir "horse_distance_stats.json") $hdFinal'
$L += 'Write-JsonSafe (Join-Path $statsDir "jockey_horse_stats.json") $jhFinal'
$L += ''
$L += '# Verify summary'
$L += 'Write-Host ""'
$L += 'Write-Host ("Jockeys: {0}" -f $jockeys.Count)'
$L += 'Write-Host ("Trainers: {0}" -f $trainers.Count)'
$L += 'Write-Host ("Horses: {0}" -f $horses.Count)'
$L += '$topJ = $jockeys.GetEnumerator() | Sort-Object { $_.Value.starts } -Descending | Select-Object -First 3'
$L += 'foreach ($t in $topJ) { Write-Host ("  J {0}: starts={1}, WR={2}%" -f $t.Key, $t.Value.starts, [math]::Round($t.Value.win_rate*100,1)) }'
$L += '$topH = $horses.GetEnumerator() | Sort-Object { $_.Value.starts } -Descending | Select-Object -First 3'
$L += 'foreach ($t in $topH) { Write-Host ("  H {0} ({1}): starts={2}" -f $t.Key, $t.Value.name, $t.Value.starts) }'
$L += ''
$L += 'Write-Host "Done."'
$L += 'exit 0'

$encBom = New-Object System.Text.UTF8Encoding $true
$outPath = Join-Path $PSScriptRoot "rebuild_aggregate.ps1"
[System.IO.File]::WriteAllText($outPath, ($L -join $C_RN), $encBom)
$joined = $L -join ""
Write-Host ("Built: {0} (lines={1}, chars={2})" -f $outPath, $L.Count, $joined.Length)
