-- v5.44: 加入晨操/試閘/近績特徵欄位
-- 用於 2026-10-07 賽事分析

ALTER TABLE race_runners ADD COLUMN IF NOT EXISTS trial_count INT DEFAULT NULL;
ALTER TABLE race_runners ADD COLUMN IF NOT EXISTS fast_work_count INT DEFAULT NULL;
ALTER TABLE race_runners ADD COLUMN IF NOT EXISTS swim_count INT DEFAULT NULL;
ALTER TABLE race_runners ADD COLUMN IF NOT EXISTS fitness_score FLOAT DEFAULT NULL;
ALTER TABLE race_runners ADD COLUMN IF NOT EXISTS fitness_label VARCHAR(20) DEFAULT NULL;
ALTER TABLE race_runners ADD COLUMN IF NOT EXISTS form_positions VARCHAR(100) DEFAULT NULL;
ALTER TABLE race_runners ADD COLUMN IF NOT EXISTS form_avg_finish FLOAT DEFAULT NULL;
ALTER TABLE race_runners ADD COLUMN IF NOT EXISTS form_best_finish INT DEFAULT NULL;
